{
 "title": "充电费用报表",
 "tags": [ "tesla_zhCN" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   {
    "name": "geofence",
    "label": "收藏点",
    "query": "SELECT name AS __text, id AS __value FROM geofences ORDER BY name COLLATE \"C\" ASC;"
   },
   {
    "name": "min_duration_min",
    "label": "Enter min duration (minutes) here",
    "query": "0"
   },
   { "name": "voltage", "label": "Enter min voltage here", "query": "0" }
  ]
 },
 "panels": [
  { "title": "$car_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "car_id" },
  {
   "title": "充电费用报表",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n    SELECT\n        (round(extract(epoch FROM start_date) - 10) * 1000) AS start_date_ts,\n        (round(extract(epoch FROM end_date) + 10) * 1000) AS end_date_ts,\n        start_date,\n        end_date,\n        CONCAT_WS(', ', COALESCE(addresses.name, nullif(CONCAT_WS(' ', addresses.road, addresses.house_number), '')), addresses.city) AS address,\n        g.name as geofence_name,\n        g.id as geofence_id,\n        p.latitude,\n        p.longitude,\n        cp.charge_energy_added,\n        cp.charge_energy_used,\n        duration_min,\n        start_battery_level,\n        end_battery_level,\n        start_[[preferred_range]]_range_km,\n        end_[[preferred_range]]_range_km,\n        outside_temp_avg,\n        cp.id,\n        lag(end_[[preferred_range]]_range_km) OVER (ORDER BY start_date) - start_[[preferred_range]]_range_km AS range_loss,\n        p.odometer - lag(p.odometer) OVER (ORDER BY start_date) AS distance,\n        cars.efficiency,\n        cp.car_id,\n        cost,\n        max(c.charger_voltage) as max_charger_voltage,\n    p.odometer as odometer\n    FROM\n        charging_processes cp\n\t  LEFT JOIN charges c ON cp.id = c.charging_process_id\n    LEFT JOIN positions p ON p.id = cp.position_id\n    LEFT JOIN cars ON cars.id = cp.car_id\n    LEFT JOIN addresses ON addresses.id = cp.address_id\n    LEFT JOIN geofences g ON g.id = geofence_id\nWHERE \n    cp.car_id = $car_id AND\n    $__timeFilter(start_date) AND\n    (cp.charge_energy_added IS NULL OR cp.charge_energy_added > 0) AND\n    ('${geofence:pipe}' = '-1' OR geofence_id in ($geofence))\nGROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17,18,21,p.odometer\nORDER BY\n    start_date\n)\nSELECT\n    start_date_ts,\n    end_date_ts,\n    CASE WHEN geofence_id IS NULL THEN CONCAT('new?lat=', latitude, '&lng=', longitude)\n         WHEN geofence_id IS NOT NULL THEN CONCAT(geofence_id, '/edit')\n    END as path,\n    car_id,\n    id,\n    -- Columns\n    start_date,\n    end_date,\n    COALESCE(geofence_name, address) as address,    \n    duration_min,\n    cost,\n    charge_energy_added,\n    charge_energy_used,\n    CASE WHEN charge_energy_used IS NULL THEN NULL ELSE LEAST(charge_energy_added / NULLIF(charge_energy_used, 0), 1.0) END as charging_efficiency,\n    convert_celsius(outside_temp_avg, '$temp_unit') AS outside_temp_avg_$temp_unit,\n    charge_energy_added * 60 / NULLIF (duration_min, 0) AS charge_energy_added_per_hour,\n    convert_km((end_[[preferred_range]]_range_km - start_[[preferred_range]]_range_km) * 60 / NULLIF (duration_min, 0), '$length_unit') AS range_added_per_hour_$length_unit,\n    start_battery_level,\n    end_battery_level,\n    convert_km(distance::numeric, '$length_unit') AS distance_$length_unit,\n    convert_km(odometer::numeric, '$length_unit') AS odometer_$length_unit\n FROM\n    data\nWHERE\n    (distance >= 0 OR distance IS NULL)\n    AND max_charger_voltage >= '$voltage'\n    AND duration_min >= '$min_duration_min'\nORDER BY\n  start_date DESC;"
    }
   ]
  },
  {
   "title": "充电电量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT start_date as \"time\", charge_energy_added\nFROM charging_processes\nWHERE \n  $__timeFilter(end_date) AND \n  car_id = $car_id AND     \n  ('${geofence:pipe}' = '-1' OR geofence_id in ($geofence))\nORDER BY start_date;"
    }
   ]
  },
  {
   "title": "使用电量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT start_date as \"time\", greatest(charge_energy_added, charge_energy_used)\nFROM charging_processes\nWHERE \n  $__timeFilter(end_date) AND \n  car_id = $car_id AND     \n  ('${geofence:pipe}' = '-1' OR geofence_id in ($geofence))\nORDER BY start_date;"
    }
   ]
  },
  {
   "title": "费用",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT start_date as \"time\", cost\nFROM charging_processes\nWHERE \n  $__timeFilter(end_date) AND \n  car_id = $car_id AND     \n  ('${geofence:pipe}' = '-1' OR geofence_id in ($geofence))\nORDER BY start_date;"
    }
   ]
  }
 ]
}